version: "3.9"
services:
  server:
    image: "rancher/k3s:latest"
    network_mode: host
    command:
      - server
    tmpfs:
      - /run
      - /var/run
    privileged: true
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    environment:
      - K3S_TOKEN=secret
      - K3S_KUBECONFIG_OUTPUT=/output/kubeconfig.yaml
      - K3S_KUBECONFIG_MODE=666
    volumes:
      - ./kubeconfig/:/output
    ports:
      - 6443:6443
      - 80:80
      - 443:443
  
