{{ $ghcr_username := required "User must be set!" .Values.ghcrStarwit.user }}
{{ $ghcr_password := required "Password must be set (can also be a token)!" .Values.ghcrStarwit.password }}

apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: ghcr-starwit
  namespace: cityos
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"ghcr.io\":{\"auth\":\"%s:%s\"}}}" $ghcr_username $ghcr_password | b64enc }}
