{{ $ghcr_username := required "User must be set!" .Values.ghcrStarwit.user }}
{{ $ghcr_password := required "Password must be set (can also be a token)!" .Values.ghcrStarwit.password }}

apiVersion: v1
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"ghcr.io\":{\"username\":\"%s\",\"password\":\"%s\",\"auth\":\"\"}}}" $ghcr_username $ghcr_password | b64enc }}
kind: Secret
metadata:
  creationTimestamp: null
  name: ghcr-starwit
type: kubernetes.io/dockerconfigjson
