environments: 
  dev-local:
    values:
      - imagePullSecret: ghcr-starwit
  
---
repositories:
- name: codecentric
  url: https://codecentric.github.io/helm-charts
- name: bitnami
  url: https://charts.bitnami.com/bitnami

releases:
  - chart: ./charts/secrets
    name: secrets
    namespace: cityos
    createNamespace: true
    values:
      - values.secrets.yaml
  - chart: ./charts/cityos
    name: cityos
    namespace: cityos
    createNamespace: true
    values:
      - imagePullSecrets:
        - name: {{ .Values.imagePullSecret }}

