# This file and its contents are licensed under the Apache License 2.0.
# Please see the included NOTICE for copyright information and LICENSE for a copy of the license.

replicaCount: 1
fullnameOverride: "{{ .Release.Name }}-timescaledb"
# This configuration will be passed on to Patroni directly, there are a few things that are
# injected/changed, these are:
#   - archive_command will be set to /bin/true if backup is disabled
#   - any context sensitive parameter (scope, namespace, name) will be overridden by the Kubernetes context
# https://patroni.readthedocs.io/en/latest/SETTINGS.html#settings
patroni:
  postgresql:
    pg_hba:
    - local     all             postgres                              peer
    - local     all             all                                   password
    - hostnossl all,replication all                all                password
    - hostssl   all             all                127.0.0.1/32       password
    - hostssl   all             all                ::1/128            password
    - hostssl   replication     standby            all                password
    - hostssl   all             all                all                password
    use_unix_socket: true
  restapi:
    listen: 0.0.0.0:8008

postInit:
  # A list of sources, that contain post init scripts.
  # https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#projectedvolumesource-v1-core
  # These scripts are all projected to the same directory and will be executed
  # in sorted order only once: After a cluster initialization
  # Some examples:
  - configMap:
      name: custom-init-scripts
      optional: true
  - secret:
      name: custom-secret-scripts
      optional: true
