imagePullSecrets:
  - name: docker-starwit-internal
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

resources: {}

videoSource:
  image: 
    repository: docker.internal.starwit-infra.de/sae/video-source-py
    tag: ""
  # configs: []
  configs: 
  - id: video1
    uri: rtsp://florian-p14s:8554/ondemand
    # This limits fps to the fps of the source (only really makes sense with video files, if a camera shall be simulated)
    useSourceFps: True
    logLevel: DEBUG

objectDetector:
  image:
    repository: docker.internal.starwit-infra.de/sae/object-detector
    tag: ""
  config:
    modelConfig:
      size: "n"
      device: cpu
    inferenceSize: [ 640, 640 ]
    classes: [ 2 ]
    logLevel: DEBUG
    redis:
      streamIds:
        - video1

objectTracker:
  image:
    repository: docker.internal.starwit-infra.de/sae/object-tracker
    tag: ""
  configs:
    - streamId: video1
      trackingParams:
        detThresh: 0.25
        modelWeights: osnet_x0_25_msmt17.pt
      device: cpu
      logLevel: DEBUG
        

redis:
  architecture: standalone
  auth:
    enabled: false
  master:
    persistence:
      enabled: false