nameOverride: ""
fullnameOverride: ""

pullSecret:
  user: user
  password: password

# extraImagePullSecrets:
#   - name: extra-pull-secret

videoSource:
  image: 
    repository: docker.internal.starwit-infra.de/sae/video-source-py
    tag: ""
  # configs: []
  configs: 
  - id: video1
    uri: 'uri'
    # This limits fps to the fps of the source (only really makes sense with video files, if a camera shall be simulated)
    useSourceFps: False
    logLevel: DEBUG

objectDetector:
  image:
    repository: docker.internal.starwit-infra.de/sae/object-detector
    tag: ""
  config:
    model:
      size: "n"
      device: cpu
    inferenceSize: [ 640, 640 ]
    classes: [ 2 ]
    logLevel: DEBUG
    redis:
      streamIds:
        - video1

objectTracker:
  image:
    repository: docker.internal.starwit-infra.de/sae/object-tracker
    tag: ""
  configs:
    - streamId: video1
      trackingParams:
        detThresh: 0.25
        modelWeights: osnet_x0_25_msmt17.pt
      device: cpu
      logLevel: DEBUG

databaseWriter:
  image:
    repository: docker.internal.starwit-infra.de/sae/vision-api-jms-client
    tag: 0.4.0
  config:
    redisStreamIds:
      - video1
    db:
      jdbcUrl: jdbc:postgresql://100.70.113.34:30001/
      schema: sae
      username: sae
      password: sae
      hypertable: detection2

redis:
  architecture: standalone
  auth:
    enabled: false
  commonConfiguration: |-
    save ""
    appendonly no
  master:
    persistence:
      enabled: false
  metrics:
    enabled: true

prometheus:
  alertmanager:
    enabled: false
  server:
    service:
      type: ClusterIP
    scrapeInterval: 10s
    evaluationInterval: 10s
    extraScrapeConfigs:
      - job_name: redis_exporter
        static_configs:
          - targets: ['{{ include "sae.redisMetricsServiceName" $ }}:9121']
      - job_name: node_exporter
        static_configs:
          - targets: ['{{ include "sae.nodeExporterServiceName" $ }}:9100']

grafana:
  admin:
    password: admin

nodeexporter:
  enabled: true