imagePullSecrets:
  - name: docker-starwit-internal
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

videoSource:
  image: 
    repository: docker.internal.starwit-infra.de/sae/video-source-py
    tag: ""
  # configs: []
  configs: 
  - id: video1
    uri: 'rtsp://vwvideo:Carmel,2021!@100.97.228.110:11554/?inst=0'
    # This limits fps to the fps of the source (only really makes sense with video files, if a camera shall be simulated)
    useSourceFps: False
    logLevel: DEBUG

objectDetector:
  image:
    repository: docker.internal.starwit-infra.de/sae/object-detector
    tag: ""
  config:
    model:
      size: "n"
      device: cuda
    inferenceSize: [ 640, 640 ]
    classes: [ 2 ]
    logLevel: DEBUG
    redis:
      streamIds:
        - video1

objectTracker:
  image:
    repository: docker.internal.starwit-infra.de/sae/object-tracker
    tag: ""
  configs:
    - streamId: video1
      trackingParams:
        detThresh: 0.25
        modelWeights: osnet_x0_25_msmt17.pt
      device: cuda
      logLevel: DEBUG

databaseWriter:
  image:
    repository: docker.internal.starwit-infra.de/sae/database-writer
    tag: ""
  config:
    redisStreamIds:
      - video1
      - video2
    db:
      jdbcUrl: jdbc:postgresql:postgres
      schema: postgres
      username: postgres
      password: postgres
      hypertable: data

redis:
  architecture: standalone
  auth:
    enabled: false
  master:
    persistence:
      enabled: false