apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik-forward-auth
  labels:
    app: traefik-forward-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik-forward-auth
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: traefik-forward-auth
    spec:
      serviceAccountName: traefik-ingress-controller
      terminationGracePeriodSeconds: 60
      containers:
        - image: thomseddon/traefik-forward-auth:2
          name: traefik-forward-auth
          ports:
            - containerPort: 4181
              protocol: TCP
          env:
            - name: DOMAIN
              value: "glacier"
            # INSECURE_COOKIE is required if not using a https entrypoint
            # - name: INSECURE_COOKIE
            #   value: "true"
            # Remove COOKIE_DOMAIN if not using auth host mode
            - name: COOKIE_DOMAIN
              value: "glacier"
            - name: AUTH_HOST
              value: "auth.glacier"
            - name: LOG_LEVEL
              value: "info"
            - name: PROVIDERS_OIDC_ISSUER_URL
              value: http://glacier/cityos-auth/realms/citydashboard
            - name: PROVIDERS_OIDC_CLIENT_ID
              value: forward-auth
            - name: PROVIDERS_OIDC_CLIENT_SECRET
              value: blubb
            - name: SECRET
              value: something-random