{{- with .Values.databaseWriter }}
{{- $imageRepo := .image.repository }}
{{- $imageTag := .image.tag }}
{{- with .config -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "sae.fullname" $ }}-database-writer
  labels:
    {{- include "sae.labels" $ | nindent 4 }}
    app.kubernetes.io/component: database-writer
spec:
  selector:
    matchLabels:
      {{- include "sae.selectorLabels" $ | nindent 6 }}
      app.kubernetes.io/component: database-writer
  template:
    metadata:
      {{- with $.Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "sae.selectorLabels" $ | nindent 8 }}
        app.kubernetes.io/component: database-writer
    spec:
      serviceAccountName: {{ include "sae.serviceAccountName" $ }}
      securityContext:
        {{- toYaml $.Values.podSecurityContext | nindent 8 }}
      containers:
        - name: database-writer
          securityContext:
            {{- toYaml $.Values.securityContext | nindent 12 }}
          image: "{{ $imageRepo }}:{{ $imageTag | default $.Chart.AppVersion }}"
          imagePullPolicy: IfNotPresent
          resources:
            {{- toYaml $.Values.resources | nindent 12 }}
          env:
            - name: DB_OUTPUT_ENABLED
              value: "true"
            - name: DB_JDBC_URL
              value: {{ .db.jdbcUrl | quote }}
            - name: DB_SCHEMA
              value: {{ .db.schema | quote }}
            - name: DB_USERNAME
              value: {{ .db.username | quote }}
            - name: DB_PASSWORD
              value: {{ .db.password | quote }}
            - name: DB_HYPERTABLE
              value: {{ .db.hypertable | quote }}
            - name: REDIS_INPUT_ENABLED
              value: "true"
            - name: REDIS_HOST
              value: {{ include "sae.redisServiceName" $ }}
            - name: REDIS_PORT
              value: {{ include "sae.redisServicePort" $ }}
            - name: REDIS_STREAM_IDS
              value: {{ join "," .redisStreamIds | quote }}
      {{- with $.Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
{{- end }}
{{- end }}
