{{- with .Values.objectTracker }}
{{- $imageRepo := .image.repository }}
{{- $imageTag := .image.tag }}
{{- range .configs }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "sae.fullname" $ }}-object-tracker-{{ .streamId }}
  labels:
    {{- include "sae.labels" $ | nindent 4 }}
    app.kubernetes.io/component: object-tracker-{{ .streamId }}
spec:
  selector:
    matchLabels:
      {{- include "sae.selectorLabels" $ | nindent 6 }}
      app.kubernetes.io/component: object-tracker-{{ .streamId }}
  template:
    metadata:
      {{- with $.Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "sae.selectorLabels" $ | nindent 8 }}
        app.kubernetes.io/component: object-tracker-{{ .streamId }}
    spec:
      serviceAccountName: {{ include "sae.serviceAccountName" $ }}
      securityContext:
        {{- toYaml $.Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ $.Chart.Name }}
          securityContext:
            {{- toYaml $.Values.securityContext | nindent 12 }}
          image: "{{ $imageRepo }}:{{ $imageTag | default $.Chart.AppVersion }}"
          imagePullPolicy: IfNotPresent
          resources:
            {{- toYaml $.Values.resources | nindent 12 }}
          env:
            - name: TRACKING_PARAMS__DET_THRESH
              value: {{ .trackingParams.detThresh | quote }}
            - name: TRACKING_PARAMS__MODEL_WEIGHTS
              value: {{ .trackingParams.modelWeights | quote }}
            - name: DEVICE
              value: {{ .device | quote }}
            - name: LOG_LEVEL
              value: {{ .logLevel | quote }}
            - name: REDIS__HOST
              value: {{ include "sae.redisServiceName" $ }}
            - name: REDIS__PORT
              value: {{ include "sae.redisServicePort" $ }}
            - name: REDIS__STREAM_ID
              value: {{ .streamId | quote }}
      {{- with $.Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
{{- end }}
{{- end }}
