apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sae.serviceAccountName" . }}
  labels:
    {{- include "sae.labels" . | nindent 4 }}
{{- with .Values.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml . | nindent 8 }}
{{- end }}
