{{- with .Values.videoSource }}
{{- $imageRepo := .image.repository }}
{{- $imageTag := .image.tag }}
{{- range .configs -}}
{{- $instanceName := printf "video-source-%s" (lower .id) }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "sae.fullname" $ }}-{{ $instanceName }}
  labels:
    {{- include "sae.labels" $ | nindent 4 }}
    app.kubernetes.io/component: video-source
spec:
  selector:
    matchLabels:
      {{- include "sae.selectorLabels" $ | nindent 6 }}
      app.kubernetes.io/component: {{ $instanceName }}
  template:
    metadata:
      {{- with $.Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "sae.selectorLabels" $ | nindent 8 }}
        app.kubernetes.io/component: {{ $instanceName }}
    spec:
      serviceAccountName: {{ include "sae.serviceAccountName" $ }}
      securityContext:
        {{- toYaml $.Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ $instanceName }}
          securityContext:
            {{- toYaml $.Values.securityContext | nindent 12 }}
          image: "{{ $imageRepo }}:{{ $imageTag | default $.Chart.AppVersion }}"
          imagePullPolicy: IfNotPresent
          resources:
            {{- toYaml $.Values.resources | nindent 12 }}
          env:
            - name: ID
              value: {{ .id | quote }}
            - name: URI
              value: {{ .uri | quote }}
            - name: MAX_FPS
              value: {{ .maxFps | quote }}
            - name: LOG_LEVEL
              value: {{ .logLevel | quote }}
            - name: REDIS__HOST
              value: {{ include "sae.redisServiceName" $ }}
            - name: REDIS__PORT
              value: {{ include "sae.redisServicePort" $ }}
      {{- with $.Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
{{- end }}
{{- end }}
