persistence:
  enabled: true
  size: 5Gi

ingress:
  enabled: true
  hosts:
    - name: helm.internal.starwit-infra.de
      tls: true
      tlsSecret: chartmuseum-tls

env:
  open:
    DISABLE_API: false
  existingSecret: chartmuseum-auth
  existingSecretMappings:
    BASIC_AUTH_USER: basic-auth-user
    BASIC_AUTH_PASS: basic-auth-pass