apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik-sso
  labels:
    app: traefik-sso
spec:
  template:
    metadata:
      labels:
        name: traefik-sso
        app: traefik-sso
        {{- include "traefik-forward-auth.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: traefik-sso
          image: thomseddon/traefik-forward-auth:2
          imagePullPolicy: Always
          env:
            - name: DEFAULT_PROVIDER
              value: oidc
            - name: PROVIDERS_OIDC_ISSUER_URL
              value: {{ .Values.forwardAuth.issuerUrl }}
            - name: PROVIDERS_OIDC_CLIENT_ID
              value: {{ .Values.forwardAuth.clientId }}
            - name: PROVIDERS_OIDC_CLIENT_SECRET
              value: {{ .Values.forwardAuth.clientSecret }}
            - name: SECRET
              value: {{ randAlphaNum 32 | b64enc | quote }}
            - name: AUTH_HOST
              value: glacier
            - name: COOKIE_DOMAIN
              value: glacier
            - name: INSECURE_COOKIE
              value: "true"
            - name: LOG_LEVEL
              value: debug
          ports:
            - containerPort: 4181
  selector:
    matchLabels:
      {{- include "traefik-forward-auth.selectorLabels" . | nindent 6 }}