apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ .Release.Name }}-forward-auth
  namespace: {{ .Release.Namespace }}
spec:
  forwardAuth:
    address: {{ .Values.frontend }}