{{/*apiVersion: apps/v1*/}}
{{/*kind: Deployment*/}}
{{/*metadata:*/}}
{{/*  name: traefik-forward-auth*/}}
{{/*  labels:*/}}
{{/*    app: traefik-forward-auth*/}}
{{/*spec:*/}}
{{/*  replicas: 1*/}}
{{/*  selector:*/}}
{{/*    matchLabels:*/}}
{{/*      app: traefik-forward-auth*/}}
{{/*  strategy:*/}}
{{/*    type: Recreate*/}}
{{/*  template:*/}}
{{/*    metadata:*/}}
{{/*      labels:*/}}
{{/*        app: traefik-forward-auth*/}}
{{/*    spec:*/}}
{{/*      terminationGracePeriodSeconds: 60*/}}
{{/*      containers:*/}}
{{/*        - image: thomseddon/traefik-forward-auth:2*/}}
{{/*          name: traefik-forward-auth*/}}
{{/*          ports:*/}}
{{/*            - containerPort: 4181*/}}
{{/*              protocol: TCP*/}}
{{/*          env:*/}}
{{/*#            - name: DOMAIN*/}}
{{/*#              value: "example.com"*/}}
{{/*            # INSECURE_COOKIE is required unless using https entrypoint*/}}
{{/*            - name: INSECURE_COOKIE*/}}
{{/*              value: "true"*/}}
{{/*            - name: DEFAULT_PROVIDER*/}}
{{/*              value: oidc*/}}
{{/*            - name: PROVIDERS_OIDC_ISSUER_URL*/}}
{{/*              value: {{ .Values.forwardAuth.issuerUrl }}*/}}
{{/*            - name: PROVIDERS_OIDC_CLIENT_ID*/}}
{{/*              value: {{ .Values.forwardAuth.clientId }}*/}}
{{/*            - name: PROVIDERS_OIDC_CLIENT_SECRET*/}}
{{/*              value: {{ .Values.forwardAuth.clientSecret }}*/}}
{{/*            - name: SECRET*/}}
{{/*              value: {{ randAlphaNum 32 | b64enc | quote }}*/}}
{{/*            - name: LOG_LEVEL*/}}
{{/*              value: debug*/}}