{{- if .Values.ingress.enabled -}}
  {{- $fullName := include "cityos-frontend.fullname" . -}}
  {{- $svcPort := .Values.service.port -}}
  {{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
  {{- else -}}
apiVersion: extensions/v1beta1
  {{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "cityos-frontend.labels" . | nindent 4 }}
  annotations:
  {{- if .Values.traefik.middleware.stripprefix }}
    traefik.ingress.kubernetes.io/router.middlewares: {{ .Release.Namespace }}-{{ .Release.Name }}-oauth-errors@kubernetescrd, {{ .Release.Namespace }}-{{ .Release.Name }}-oauth-auth@kubernetescrd, {{ .Release.Namespace }}-{{ .Release.Name }}-strip-prefix@kubernetescrd
  {{- end }}
  {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}

spec:
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
          {{- end }}
    {{- end }}
  {{- end }}
# https://brianturchyn.net/traefik-forwardauth-support-with-keycloak/
# https://doc.traefik.io/traefik/routing/providers/kubernetes-ingress/
# https://github.com/thomseddon/traefik-forward-auth