apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-init-scripts
data:
  custom-config.sh: |-
    #!/bin/bash

    psql -d "$1" <<__SQL__
    CREATE ROLE hackathon WITH LOGIN;
    CREATE DATABASE hackathon OWNER hackathon;
    __SQL__

    psql -d "$1" <<__SQL__
    CREATE ROLE citydashboard WITH LOGIN;
    CREATE DATABASE citydashboard OWNER citydashboard;
    __SQL__

