repositories:
- name: timescale
  url: https://charts.timescale.com

releases:
  - name: pgadmin4
    chart: runix/pgadmin4
    inherit:
      - template: defaultns
    values:
      - ../env/{{ .Environment.Name }}/pgadmin4-values.yaml

  - name: timescale-config
    chart: ../../charts/timescale-config
    inherit:
      - template: defaultns

  - name: timescale
    chart: timescale/timescaledb-single
    values:
      - ../env/{{ .Environment.Name }}/timescale-values.yaml
    inherit:
      - template: defaultns
    needs:
      - timescale-config