repositories:
- name: timescale
  url: https://charts.timescale.com

releases:
  - name: pgadmin4
    chart: runix/pgadmin4
    inherit:
      - template: defaultns
    values:
      - ../timescale/values/pgadmin4-values.yaml.gotmpl

  - name: timescale-config
    chart: ../../charts/timescale-config
    inherit:
      - template: defaultns

  - name: timescale
    chart: timescale/timescaledb-single
    values:
      - ../timescale/values/timescale-values.yaml.gotmpl
    inherit:
      - template: defaultns
    needs:
      - timescale-config