---
# Source: secrets/templates/ghcr-starwit-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: ghcr-starwit
  namespace: cityos
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoibXlnaXRodWJ1c2VyIiwicGFzc3dvcmQiOiJteWdpdHVicGF0IiwiYXV0aCI6IiJ9fX0=
